name: Gen Github Snake

on:
  # each day
  schedule:
    - cron: "0 0 * * *"

  # run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake.svg?palette=github-light
            github-snake-dark.svg?palette=github-dark
      # push the snakes to a GitHub Gist
      - name: Push snake to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 49c7e88f47a921045ef17baee55e1f05
          gist_file_name: github-snake.svg
          file_path: github-snake.svg
      - name: Push dark snake to gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: 49c7e88f47a921045ef17baee55e1f05
          gist_file_name: github-snake-dark.svg
          file_path: github-snake-dark.svg
